spring.application.name=diakonpay
spring.config.import=optional:classpath:.env[.properties]
spring.output.ansi.enabled=always

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

diakonpay.mail.reply=${MAIL_REPLY}

spring.datasource.url=jdbc:postgresql://localhost:6667/budget_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

tarantool.host=${TARANTOOL_HOST:localhost}
tarantool.port=${TARANTOOL_PORT:3301}
tarantool.user=${TARANTOOL_USER:admin}
tarantool.password=${TARANTOOL_PASSWORD:tarantool_secret}

jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000